#!usr/bin/python

print("What is your password time delayed parameter preference?: ")
TP = input()
Password = input('Please Enter a Password -->  ')


print ("Please re-enter password -->   ")
TimeDelay = str(input())
if Password in TimeDelay:
        print('It worked and recognized that you entered 5 as a time delay parameter')
else:
        print('The password did not recognize any time delay parameter or the passwords did not match')

